### ISSUE TITLE
where is the package?

### ISSUE THREAD

**Issue by xiahuan357** [rprakitpong/HoloAssemblyTrainer#1]
1. There is no package to import.
2. some error in the sampleproject-hololens.
![image](https://user-images.githubusercontent.com/11535384/83742657-46b32800-a68c-11ea-9b57-8ed6f0249657.png)

**Comment by rprakitpong** [comment]
1. Which package are you referencing?
2. Seems like those errors are associated with Vuforia. You need to import Vuforia into your project.

**Comment by rprakitpong** [comment]
If you want the sample project to work more reliably, build it in Android. There's some issues with how MRTK interact with the prefab. I didn't get around to fixing it.

**Comment by xiahuan357** [comment]
thanks for reply!
I want to see how it works , Would you like to show me how it works? some pics or words?
I really want to reference your work! 
Thanks a lot!

**Comment by rprakitpong** [comment]
If you just want to see how it works, you can:
1. load /SampleProject/SampleProject/Build/Android/v00.apk into an Android device,
2. 3D print one of each stl files from /SampleAssembly/PrintFiles/,
3. print out /SampleProject/ImageTarget/printable.pdf on letter paper,
4. cut out one of the image targets, and glue it onto the 45deg-slanted plate on AssemBase.stl
4.1 I can't remember which orientation you should glue the image target in, so use the app you loaded to your Android device to help (if you point your camera to the image target, a green transparent-ish model of AssemBase should appear on screen, so just align the IRL AssemBase to on-screen AssemBase),
5. there's a next button on screen, so if you follow along it, it'll tell you how to assemble the rest of the parts.
If you don't have a 3D printer, you can just point your camera to the image target and you'll still see all the models floating around to show you how to assemble the parts, but you lose some usefulness of it being overlaid on top of real life objects (which is where it stands out from a 3D video or a book instruction, tbh).

The prefab itself is fairly simple as well, so you can just load it to your own Unity project and hook it up to Vuforia+MRTK project that you have set up.

Can I ask you what you are looking at this for? Hobby? Work? School? Etc?

**Comment by xiahuan357** [comment]
For research, Thanks a lot!





发自我的iPhone


------------------ Original ------------------
